### ISSUE TITLE
CI support contribution

### ISSUE THREAD

**Issue by john-mejia** [erikvillegas/itunes-connect-slack#8]
Hi, I'm using this project to get app status updates through our circleCI setup, I changes the polling to just fetch once and have it running every X minutes through CI (circle). I'd like to submit a PR but wanted to know if you'd be open to this change so we can continue using this project instead of duplicating it.

The changes would be:
* add a new way to execute this so it doesn't poll, just runs once. 
* adds a circle config file with 1 workflow that runs on cron, using circle caching we can achieve database persistence.
* sets the channel name to a ENV var, so it doesn't have to be committed to the project.

**Comment by erikvillegas** [comment]
Absolutely! I don't really maintain this project anymore but I'm happy to merge in the code if it'll help other CircleCI users.
